// Server-side only. Generated by scripts/build-guest-data.mjs from the
// "Ben and Emily Wedding Guest Tracker" sheet — do not hand-edit the bulk of
// this file, re-run the script instead. This file is read by the /api
// serverless functions and is NEVER imported from src/, so it does not get
// bundled into the public site's JS.
//
// Households flagged with a placeholder "Guest" member are ones where the
// sheet's invite line didn't spell out every attendee's real name (e.g.
// "Mr. and Mrs. X", "The X Family", "X and Guest"). See the importer's
// console output for the full list — fix names directly below as you learn
// them, or update the sheet and re-run the script.

// The wedding itself is not listed in any household's `events` — every
// invitation includes it — but it is defined here so the RSVP form can show
// the same date/time/venue detail for it as for the Friday events.
export const WEDDING_EVENT = {
  key: "wedding",
  label: "Wedding Ceremony & Reception",
  date: "Saturday, October 24, 2026",
  time: "4:30 PM",
  venue: "Christ Episcopal Church, then Rosemont Farm",
  attire: "Black Tie Optional"
};

export const EVENT_DEFINITIONS = {
  rehearsal: {
    label: "Rehearsal Dinner",
    date: "Friday, October 23, 2026",
    time: "5:30 PM",
    venue: "Farmington Country Club",
    attire: "Cocktail Attire"
  },
  welcome: {
    label: "Welcome Party",
    date: "Friday, October 23, 2026",
    time: "8:00 PM",
    venue: "Farmington Country Club",
    attire: "Cocktail Attire"
  }
};

// Entrée choices for the Saturday reception dinner at Rosemont Farm.
export const MEAL_OPTIONS = ["Steak", "Salmon", "Vegetarian"];

// What each guest wants poured for the toast at the reception.
export const TOAST_OPTIONS = ["Bourbon", "Champagne", "Non Alcoholic Apple Cider"];

export const GUESTS = [
  {
    "id": "atwell-bridget",
    "members": [
      {
        "firstName": "Bridget",
        "lastName": "Atwell"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "barnes-guest-1",
    "members": [
      {
        "firstName": "Guest 1",
        "lastName": "Barnes",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Barnes",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Barnes",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 4",
        "lastName": "Barnes",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "barry-christopher",
    "members": [
      {
        "firstName": "Christopher",
        "lastName": "Barry"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bermudez-esteban",
    "members": [
      {
        "firstName": "Esteban",
        "lastName": "Bermudez"
      },
      {
        "firstName": "Guest",
        "lastName": "Bermudez",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "berry-mike",
    "members": [
      {
        "firstName": "Mike",
        "lastName": "Berry"
      },
      {
        "firstName": "Guest",
        "lastName": "Berry",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "berry-fritz",
    "members": [
      {
        "firstName": "Fritz",
        "lastName": "Berry"
      },
      {
        "firstName": "Guest",
        "lastName": "Berry",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bienen-esayian-nicholas",
    "members": [
      {
        "firstName": "Nicholas",
        "lastName": "Bienen-Esayian"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "billings-lisa",
    "members": [
      {
        "firstName": "Lisa",
        "lastName": "Billings"
      },
      {
        "firstName": "Guest",
        "lastName": "Billings",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "billings-nicholas",
    "members": [
      {
        "firstName": "Nicholas",
        "lastName": "Billings"
      },
      {
        "firstName": "Guest",
        "lastName": "Billings",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bladt-william",
    "members": [
      {
        "firstName": "William",
        "lastName": "Bladt"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Bladt",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Bladt",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Bladt",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bodman-charlie",
    "members": [
      {
        "firstName": "Charlie",
        "lastName": "Bodman"
      },
      {
        "firstName": "Perri",
        "lastName": "Bodman"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "boedecker-ingrid",
    "members": [
      {
        "firstName": "Ingrid",
        "lastName": "Boedecker"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "brebach-greg",
    "members": [
      {
        "firstName": "Greg",
        "lastName": "Brebach"
      },
      {
        "firstName": "Elissa",
        "lastName": "Brebach"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Brebach",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Brebach",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "brebach-gresham",
    "members": [
      {
        "firstName": "Gresham",
        "lastName": "Brebach"
      },
      {
        "firstName": "Judy",
        "lastName": "Brebach"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "brebach-mark",
    "members": [
      {
        "firstName": "Mark",
        "lastName": "Brebach"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "brookshire-matt",
    "members": [
      {
        "firstName": "Matt",
        "lastName": "Brookshire"
      },
      {
        "firstName": "Guest",
        "lastName": "Brookshire",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "brookshire-madeline",
    "members": [
      {
        "firstName": "Madeline",
        "lastName": "Brookshire"
      },
      {
        "firstName": "Guest",
        "lastName": "Brookshire",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "brown-tyler",
    "members": [
      {
        "firstName": "Tyler",
        "lastName": "Brown"
      },
      {
        "firstName": "Guest",
        "lastName": "Brown",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "calzaretta-john",
    "members": [
      {
        "firstName": "John",
        "lastName": "Calzaretta"
      },
      {
        "firstName": "Guest",
        "lastName": "Calzaretta",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "carpenter-charles",
    "members": [
      {
        "firstName": "Charles",
        "lastName": "Carpenter"
      },
      {
        "firstName": "Elizabeth",
        "lastName": "Berner"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "carpenter-edmund-mogford",
    "members": [
      {
        "firstName": "Edmund Mogford",
        "lastName": "Carpenter Jr"
      },
      {
        "firstName": "Guest",
        "lastName": "Carpenter Jr",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "collins-christine",
    "members": [
      {
        "firstName": "Christine",
        "lastName": "Collins"
      },
      {
        "firstName": "Stephen",
        "lastName": "Collins"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "collins-mary-jo",
    "members": [
      {
        "firstName": "Mary Jo",
        "lastName": "Collins"
      },
      {
        "firstName": "Andrew",
        "lastName": "Collins"
      },
      {
        "firstName": "Wyatt",
        "lastName": "Collins"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "collins-patrick",
    "members": [
      {
        "firstName": "Patrick",
        "lastName": "Collins"
      },
      {
        "firstName": "Guest",
        "lastName": "Collins",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "collins-stephen",
    "members": [
      {
        "firstName": "Stephen",
        "lastName": "Collins"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Collins",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Collins",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Collins",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 4",
        "lastName": "Collins",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "danzi-mark",
    "members": [
      {
        "firstName": "Mark",
        "lastName": "Danzi"
      },
      {
        "firstName": "Guest",
        "lastName": "Danzi",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "davis-brad",
    "members": [
      {
        "firstName": "Brad",
        "lastName": "Davis"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "davis-guest-1",
    "members": [
      {
        "firstName": "Guest 1",
        "lastName": "Davis",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Davis",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dearman-ken",
    "members": [
      {
        "firstName": "Ken",
        "lastName": "Dearman"
      },
      {
        "firstName": "Anthony",
        "lastName": "Dearman"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "defilippo-camryn",
    "members": [
      {
        "firstName": "Camryn",
        "lastName": "DeFilippo"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "devito-cooper",
    "members": [
      {
        "firstName": "Cooper",
        "lastName": "Devito"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "devito-tate",
    "members": [
      {
        "firstName": "Tate",
        "lastName": "Devito"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "devito-lesli",
    "members": [
      {
        "firstName": "Lesli",
        "lastName": "Devito"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dickinson-cole",
    "members": [
      {
        "firstName": "Cole",
        "lastName": "Dickinson"
      },
      {
        "firstName": "Ellie",
        "lastName": "Dickinson"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "dickinson-t-m",
    "members": [
      {
        "firstName": "T.M.",
        "lastName": "Dickinson"
      },
      {
        "firstName": "Guest",
        "lastName": "Dickinson",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dickinson-tee",
    "members": [
      {
        "firstName": "Tee",
        "lastName": "Dickinson"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dillard-ian",
    "members": [
      {
        "firstName": "Ian",
        "lastName": "Dillard"
      },
      {
        "firstName": "Guest",
        "lastName": "Dillard",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dilliard-reggie",
    "members": [
      {
        "firstName": "Reggie",
        "lastName": "Dilliard"
      },
      {
        "firstName": "Jennifer",
        "lastName": "Dilliard"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "dosey-jordan",
    "members": [
      {
        "firstName": "Jordan",
        "lastName": "Dosey"
      },
      {
        "firstName": "Grace",
        "lastName": "Dosey"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "drometer-todd",
    "members": [
      {
        "firstName": "Todd",
        "lastName": "Drometer"
      },
      {
        "firstName": "Guest",
        "lastName": "Drometer",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "eissler-mark",
    "members": [
      {
        "firstName": "Mark",
        "lastName": "Eissler"
      },
      {
        "firstName": "Guest",
        "lastName": "Eissler",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "emerson-ezekiel",
    "members": [
      {
        "firstName": "Ezekiel",
        "lastName": "Emerson"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "fecsko-joseph",
    "members": [
      {
        "firstName": "Joseph",
        "lastName": "Fecsko"
      },
      {
        "firstName": "Guest",
        "lastName": "Fecsko",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "fife-david",
    "members": [
      {
        "firstName": "David",
        "lastName": "Fife"
      },
      {
        "firstName": "Marian",
        "lastName": "Fife"
      },
      {
        "firstName": "Jack",
        "lastName": "Fife"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "franz-thomas",
    "members": [
      {
        "firstName": "Thomas",
        "lastName": "Franz"
      },
      {
        "firstName": "Guest",
        "lastName": "Franz",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "freedman-wendy",
    "members": [
      {
        "firstName": "Wendy",
        "lastName": "Freedman"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "garnett-emerson",
    "members": [
      {
        "firstName": "Emerson",
        "lastName": "Garnett"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "geismer-michael",
    "members": [
      {
        "firstName": "Michael",
        "lastName": "Geismer"
      },
      {
        "firstName": "Guest",
        "lastName": "Geismer",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "geraghty-george",
    "members": [
      {
        "firstName": "George",
        "lastName": "Geraghty"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "gibbons-joel",
    "members": [
      {
        "firstName": "Joel",
        "lastName": "Gibbons"
      },
      {
        "firstName": "Bunny",
        "lastName": "Gibbons"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "gibbons-woods",
    "members": [
      {
        "firstName": "Woods",
        "lastName": "Gibbons"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "goldstern-joshua-a",
    "members": [
      {
        "firstName": "Joshua A",
        "lastName": "Goldstern"
      },
      {
        "firstName": "Anna",
        "lastName": "Rosing"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "greene-landon",
    "members": [
      {
        "firstName": "Landon",
        "lastName": "Greene"
      },
      {
        "firstName": "Guest",
        "lastName": "Greene",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "greene-cameron",
    "members": [
      {
        "firstName": "Cameron",
        "lastName": "Greene"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "greene-davis",
    "members": [
      {
        "firstName": "Davis",
        "lastName": "Greene"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "greene-sharon",
    "members": [
      {
        "firstName": "Sharon",
        "lastName": "Greene"
      },
      {
        "firstName": "Mallory",
        "lastName": "Greene"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "groome-peter",
    "members": [
      {
        "firstName": "Peter",
        "lastName": "Groome"
      },
      {
        "firstName": "Guest",
        "lastName": "Groome",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hamilton-donald-ross",
    "members": [
      {
        "firstName": "Donald Ross",
        "lastName": "Hamilton Jr"
      },
      {
        "firstName": "Guest",
        "lastName": "Hamilton Jr",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hamilton-marshall",
    "members": [
      {
        "firstName": "Marshall",
        "lastName": "Hamilton"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Hamilton",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Hamilton",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Hamilton",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "hamilton-david-ross",
    "members": [
      {
        "firstName": "David Ross",
        "lastName": "Hamilton"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hamilton-william-kearns",
    "members": [
      {
        "firstName": "William Kearns",
        "lastName": "Hamilton"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "harris-stuart-horsley",
    "members": [
      {
        "firstName": "Stuart Horsley",
        "lastName": "Harris III"
      },
      {
        "firstName": "Guest",
        "lastName": "Harris III",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "heald-sam",
    "members": [
      {
        "firstName": "Sam",
        "lastName": "Heald"
      },
      {
        "firstName": "Rebekah",
        "lastName": "Doochin"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hegemier-matthew",
    "members": [
      {
        "firstName": "Matthew",
        "lastName": "Hegemier"
      },
      {
        "firstName": "Guest",
        "lastName": "Hegemier",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "herndon-oliver",
    "members": [
      {
        "firstName": "Oliver",
        "lastName": "Herndon"
      },
      {
        "firstName": "Coleman",
        "lastName": "Lucas"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "herndon-sam",
    "members": [
      {
        "firstName": "Sam",
        "lastName": "Herndon"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "holmes-hobby",
    "members": [
      {
        "firstName": "Hobby",
        "lastName": "Holmes"
      },
      {
        "firstName": "Guest",
        "lastName": "Holmes",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "horak-thomas",
    "members": [
      {
        "firstName": "Thomas",
        "lastName": "Horak"
      },
      {
        "firstName": "Guest",
        "lastName": "Horak",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hurley-charles",
    "members": [
      {
        "firstName": "Charles",
        "lastName": "Hurley"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Hurley",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Hurley",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Hurley",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "johan-christopher",
    "members": [
      {
        "firstName": "Christopher",
        "lastName": "Johan"
      },
      {
        "firstName": "Guest",
        "lastName": "Johan",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "johan-paul",
    "members": [
      {
        "firstName": "Paul",
        "lastName": "Johan"
      },
      {
        "firstName": "Guest",
        "lastName": "Johan",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "johan-carter",
    "members": [
      {
        "firstName": "Carter",
        "lastName": "Johan"
      },
      {
        "firstName": "Guest",
        "lastName": "Johan",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "johnston-richard",
    "members": [
      {
        "firstName": "Richard",
        "lastName": "Johnston"
      },
      {
        "firstName": "Guest",
        "lastName": "Johnston",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "jones-thad",
    "members": [
      {
        "firstName": "Thad",
        "lastName": "Jones"
      },
      {
        "firstName": "Guest",
        "lastName": "Jones",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "kessinger-jonathan",
    "members": [
      {
        "firstName": "Jonathan",
        "lastName": "Kessinger"
      },
      {
        "firstName": "Guest",
        "lastName": "Kessinger",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "kilgallon-john",
    "members": [
      {
        "firstName": "John",
        "lastName": "Kilgallon"
      },
      {
        "firstName": "Guest",
        "lastName": "Kilgallon",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "kilgallon-jack",
    "members": [
      {
        "firstName": "Jack",
        "lastName": "Kilgallon"
      },
      {
        "firstName": "Guest",
        "lastName": "Kilgallon",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "kochard-larry",
    "members": [
      {
        "firstName": "Larry",
        "lastName": "Kochard"
      },
      {
        "firstName": "Guest",
        "lastName": "Kochard",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "krakower-adam",
    "members": [
      {
        "firstName": "Adam",
        "lastName": "Krakower"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "kreienbaum-tony",
    "members": [
      {
        "firstName": "Tony",
        "lastName": "Kreienbaum"
      },
      {
        "firstName": "Katy",
        "lastName": "Kreienbaum"
      },
      {
        "firstName": "Anna",
        "lastName": "Kreienbaum",
        "eventExclusions": [
          "rehearsal"
        ]
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "kreienbaum-henry",
    "members": [
      {
        "firstName": "Henry",
        "lastName": "Kreienbaum"
      },
      {
        "firstName": "Greer",
        "lastName": "Saunders"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "laing-chris",
    "members": [
      {
        "firstName": "Chris",
        "lastName": "Laing"
      },
      {
        "firstName": "Guest 1",
        "lastName": "Laing",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Laing",
        "placeholder": true,
        "placeholderKind": "guest"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Laing",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "lesemann-reenst",
    "members": [
      {
        "firstName": "Reenst",
        "lastName": "Lesemann"
      },
      {
        "firstName": "Guest",
        "lastName": "Lesemann",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "louis-fisher",
    "members": [
      {
        "firstName": "Fisher",
        "lastName": "Louis"
      },
      {
        "firstName": "Guest",
        "lastName": "Louis",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "lowe-courtney",
    "members": [
      {
        "firstName": "Courtney",
        "lastName": "Lowe"
      },
      {
        "firstName": "Guest",
        "lastName": "Lowe",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "lowe-caitlyn",
    "members": [
      {
        "firstName": "Caitlyn",
        "lastName": "Lowe"
      },
      {
        "firstName": "Sam",
        "lastName": "Rodiger"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "mackey-brett",
    "members": [
      {
        "firstName": "Brett",
        "lastName": "Mackey"
      },
      {
        "firstName": "Megan",
        "lastName": "McBride"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "maurer-james",
    "members": [
      {
        "firstName": "James",
        "lastName": "Maurer"
      },
      {
        "firstName": "Guest",
        "lastName": "Maurer",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "mcgee-abby",
    "members": [
      {
        "firstName": "Abby",
        "lastName": "McGee"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "mcneese-james-c",
    "members": [
      {
        "firstName": "James C.",
        "lastName": "McNeese"
      },
      {
        "firstName": "Guest",
        "lastName": "McNeese",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "meadow-cary",
    "members": [
      {
        "firstName": "Cary",
        "lastName": "Meadow"
      },
      {
        "firstName": "Guest",
        "lastName": "Meadow",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "miller-scott",
    "members": [
      {
        "firstName": "Scott",
        "lastName": "Miller"
      },
      {
        "firstName": "Guest",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "miller-guest-1",
    "members": [
      {
        "firstName": "Guest 1",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 4",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 5",
        "lastName": "Miller",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "montgomery-kelly",
    "members": [
      {
        "firstName": "Kelly",
        "lastName": "Montgomery"
      },
      {
        "firstName": "Guest",
        "lastName": "Montgomery",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "myers-wallin",
    "members": [
      {
        "firstName": "Wallin",
        "lastName": "Myers"
      },
      {
        "firstName": "Guest",
        "lastName": "Myers",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "nadler-matthew",
    "members": [
      {
        "firstName": "Matthew",
        "lastName": "Nadler"
      },
      {
        "firstName": "Nicholas",
        "lastName": "Bienen-Esayian"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "nicholson-steve",
    "members": [
      {
        "firstName": "Steve",
        "lastName": "Nicholson"
      },
      {
        "firstName": "Guest",
        "lastName": "Nicholson",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "northington-robert",
    "members": [
      {
        "firstName": "Robert",
        "lastName": "Northington"
      },
      {
        "firstName": "Guest",
        "lastName": "Northington",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "northington-banks",
    "members": [
      {
        "firstName": "Banks",
        "lastName": "Northington"
      },
      {
        "firstName": "Caroline",
        "lastName": "Hartigan"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "oken-glenn",
    "members": [
      {
        "firstName": "Glenn",
        "lastName": "Oken"
      },
      {
        "firstName": "Guest",
        "lastName": "Oken",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "o-leary-kerin",
    "members": [
      {
        "firstName": "Kerin",
        "lastName": "O'Leary"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "page-hughes",
    "members": [
      {
        "firstName": "Hughes",
        "lastName": "Page"
      },
      {
        "firstName": "Kade",
        "lastName": "Schwabacher"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "parker-lilly",
    "members": [
      {
        "firstName": "Lilly",
        "lastName": "Parker"
      },
      {
        "firstName": "Guest",
        "lastName": "Parker",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "plumb-william",
    "members": [
      {
        "firstName": "William",
        "lastName": "Plumb"
      },
      {
        "firstName": "Guest",
        "lastName": "Plumb",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "rardin-amy",
    "members": [
      {
        "firstName": "Amy",
        "lastName": "Rardin"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-gage",
    "members": [
      {
        "firstName": "Gage",
        "lastName": "Reichert"
      },
      {
        "firstName": "Guest",
        "lastName": "Reichert",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-hunter",
    "members": [
      {
        "firstName": "Hunter",
        "lastName": "Reichert"
      },
      {
        "firstName": "Guest",
        "lastName": "Reichert",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "reichert-kyle",
    "members": [
      {
        "firstName": "Kyle",
        "lastName": "Reichert"
      },
      {
        "firstName": "Sarah",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "reichert-jonathan-charles",
    "members": [
      {
        "firstName": "Jonathan Charles",
        "lastName": "Reichert"
      },
      {
        "firstName": "Elise",
        "lastName": "Calzaretta"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "reichert-angus",
    "members": [
      {
        "firstName": "Angus",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-griffin",
    "members": [
      {
        "firstName": "Griffin",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-fox",
    "members": [
      {
        "firstName": "Fox",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-gresham-harrison",
    "members": [
      {
        "firstName": "Gresham Harrison",
        "lastName": "Reichert"
      },
      {
        "firstName": "Olivia",
        "lastName": "Rentz"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "reichert-william-jackson",
    "members": [
      {
        "firstName": "William Jackson",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "reichert-tyler",
    "members": [
      {
        "firstName": "Tyler",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reichert-eve",
    "members": [
      {
        "firstName": "Eve",
        "lastName": "Reichert"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reid-john-barlow",
    "members": [
      {
        "firstName": "John Barlow",
        "lastName": "Reid"
      },
      {
        "firstName": "Sarah",
        "lastName": "Smith"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reiss-josh",
    "members": [
      {
        "firstName": "Josh",
        "lastName": "Reiss"
      },
      {
        "firstName": "Maggie",
        "lastName": "Lavoie"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "reiter-garrett",
    "members": [
      {
        "firstName": "Garrett",
        "lastName": "Reiter"
      },
      {
        "firstName": "Guest",
        "lastName": "Reiter",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "rittinger-kristy",
    "members": [
      {
        "firstName": "Kristy",
        "lastName": "Rittinger"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "romness-mark",
    "members": [
      {
        "firstName": "Mark",
        "lastName": "Romness"
      },
      {
        "firstName": "Christine",
        "lastName": "Romness"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "romness-brandon-watt",
    "members": [
      {
        "firstName": "Brandon Watt",
        "lastName": "Romness"
      },
      {
        "firstName": "Anna",
        "lastName": "Romness"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "romness-william",
    "members": [
      {
        "firstName": "William",
        "lastName": "Romness"
      },
      {
        "firstName": "Guest",
        "lastName": "Romness",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "romness-jane",
    "members": [
      {
        "firstName": "Jane",
        "lastName": "Romness"
      },
      {
        "firstName": "Guest",
        "lastName": "Romness",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "rutledge-doesy",
    "members": [
      {
        "firstName": "Doesy",
        "lastName": "Rutledge"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "schaeffer-guest-1",
    "members": [
      {
        "firstName": "Guest 1",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 4",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 5",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 6",
        "lastName": "Schaeffer",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "schotta-john",
    "members": [
      {
        "firstName": "John",
        "lastName": "Schotta"
      },
      {
        "firstName": "Guest",
        "lastName": "Schotta",
        "placeholder": true,
        "placeholderKind": "plus-one"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "schotta-rob",
    "members": [
      {
        "firstName": "Rob",
        "lastName": "Schotta"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "schotta-robert",
    "members": [
      {
        "firstName": "Robert",
        "lastName": "Schotta"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "schotta-carter",
    "members": [
      {
        "firstName": "Carter",
        "lastName": "Schotta"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "sezon-jeannine",
    "members": [
      {
        "firstName": "Jeannine",
        "lastName": "Sezon"
      },
      {
        "firstName": "Guest",
        "lastName": "Sezon",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "shope-sami",
    "members": [
      {
        "firstName": "Sami",
        "lastName": "Shope"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "spadaccini-matt-baffuto",
    "members": [
      {
        "firstName": "Matt Baffuto",
        "lastName": "Spadaccini"
      },
      {
        "firstName": "Erin",
        "lastName": "Spadaccini"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "stalfort-sean",
    "members": [
      {
        "firstName": "Sean",
        "lastName": "Stalfort"
      },
      {
        "firstName": "Guest",
        "lastName": "Stalfort",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "takes-craig",
    "members": [
      {
        "firstName": "Craig",
        "lastName": "Takes"
      },
      {
        "firstName": "Heather",
        "lastName": "Takes-Trees"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "tepper-andrew",
    "members": [
      {
        "firstName": "Andrew",
        "lastName": "Tepper"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "thompson-bryan",
    "members": [
      {
        "firstName": "Bryan",
        "lastName": "Thompson"
      },
      {
        "firstName": "Guest",
        "lastName": "Thompson",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "turnbull-lauren",
    "members": [
      {
        "firstName": "Lauren",
        "lastName": "Turnbull"
      },
      {
        "firstName": "Cole",
        "lastName": "Martin"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "turnbull-guest-1",
    "members": [
      {
        "firstName": "Guest 1",
        "lastName": "Turnbull",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 2",
        "lastName": "Turnbull",
        "placeholder": true,
        "placeholderKind": "family"
      },
      {
        "firstName": "Guest 3",
        "lastName": "Turnbull",
        "placeholder": true,
        "placeholderKind": "family"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "venable-andrew",
    "members": [
      {
        "firstName": "Andrew",
        "lastName": "Venable"
      },
      {
        "firstName": "Guest",
        "lastName": "Venable",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "walsh-andrew",
    "members": [
      {
        "firstName": "Andrew",
        "lastName": "Walsh"
      },
      {
        "firstName": "Guest",
        "lastName": "Walsh",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "warren-vaden",
    "members": [
      {
        "firstName": "Vaden",
        "lastName": "Warren"
      },
      {
        "firstName": "Guest",
        "lastName": "Warren",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "williams-elizabeth",
    "members": [
      {
        "firstName": "Elizabeth",
        "lastName": "Williams"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "williamson-john-paul",
    "members": [
      {
        "firstName": "John Paul",
        "lastName": "Williamson"
      },
      {
        "firstName": "Guest",
        "lastName": "Williamson",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "wright-bryan",
    "members": [
      {
        "firstName": "Bryan",
        "lastName": "Wright"
      },
      {
        "firstName": "Katy",
        "lastName": "Wright"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "wright-spencer",
    "members": [
      {
        "firstName": "Spencer",
        "lastName": "Wright"
      },
      {
        "firstName": "Guest",
        "lastName": "Wright",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "xiang-justin",
    "members": [
      {
        "firstName": "Justin",
        "lastName": "Xiang"
      },
      {
        "firstName": "Guest",
        "lastName": "Xiang",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "yarborough-matthew",
    "members": [
      {
        "firstName": "Matthew",
        "lastName": "Yarborough"
      },
      {
        "firstName": "Guest",
        "lastName": "Yarborough",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "young-matthew",
    "members": [
      {
        "firstName": "Matthew",
        "lastName": "Young"
      },
      {
        "firstName": "Guest",
        "lastName": "Young",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ],
    "qualifier": "FL"
  },
  {
    "id": "young-matthew-2",
    "members": [
      {
        "firstName": "Matthew",
        "lastName": "Young"
      },
      {
        "firstName": "Guest",
        "lastName": "Young",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ],
    "qualifier": "OH"
  },
  {
    "id": "young-oliver",
    "members": [
      {
        "firstName": "Oliver",
        "lastName": "Young"
      },
      {
        "firstName": "Guest",
        "lastName": "Young",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "young-chloe",
    "members": [
      {
        "firstName": "Chloe",
        "lastName": "Young"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "young-stephen",
    "members": [
      {
        "firstName": "Stephen",
        "lastName": "Young"
      },
      {
        "firstName": "Guest",
        "lastName": "Young",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "mcneese-james",
    "members": [
      {
        "firstName": "James",
        "lastName": "McNeese II"
      },
      {
        "firstName": "Luke",
        "lastName": "McNeese"
      },
      {
        "firstName": "Lance",
        "lastName": "McNeese"
      }
    ],
    "events": [
      "rehearsal",
      "welcome"
    ]
  },
  {
    "id": "crawford-wilson",
    "members": [
      {
        "firstName": "Wilson",
        "lastName": "Crawford"
      },
      {
        "firstName": "Guest",
        "lastName": "Crawford",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "wood-hunter",
    "members": [
      {
        "firstName": "Hunter",
        "lastName": "Wood"
      },
      {
        "firstName": "Guest",
        "lastName": "Wood",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "jones-donna-hall",
    "members": [
      {
        "firstName": "Donna Hall",
        "lastName": "Jones"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hanggi-bob",
    "members": [
      {
        "firstName": "Bob",
        "lastName": "Hanggi"
      },
      {
        "firstName": "Guest",
        "lastName": "Hanggi",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "breeden-richard",
    "members": [
      {
        "firstName": "Richard",
        "lastName": "Breeden"
      },
      {
        "firstName": "Guest",
        "lastName": "Breeden",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "smith-mickey",
    "members": [
      {
        "firstName": "Mickey",
        "lastName": "Smith"
      },
      {
        "firstName": "Guest",
        "lastName": "Smith",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "carroll-connie-craig",
    "members": [
      {
        "firstName": "Connie Craig",
        "lastName": "Carroll"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bays-stephen",
    "members": [
      {
        "firstName": "Stephen",
        "lastName": "Bays"
      },
      {
        "firstName": "Guest",
        "lastName": "Bays",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "bond-cory",
    "members": [
      {
        "firstName": "Cory",
        "lastName": "Bond"
      },
      {
        "firstName": "Guest",
        "lastName": "Bond",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "costa-mary",
    "members": [
      {
        "firstName": "Mary",
        "lastName": "Costa"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "hunt-tommy",
    "members": [
      {
        "firstName": "Tommy",
        "lastName": "Hunt"
      },
      {
        "firstName": "Guest",
        "lastName": "Hunt",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "howard-michael",
    "members": [
      {
        "firstName": "Michael",
        "lastName": "Howard"
      },
      {
        "firstName": "Guest",
        "lastName": "Howard",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "mcneese-larry",
    "members": [
      {
        "firstName": "Larry",
        "lastName": "McNeese"
      },
      {
        "firstName": "Guest",
        "lastName": "McNeese",
        "placeholder": true,
        "placeholderKind": "guest"
      }
    ],
    "events": [
      "welcome"
    ]
  },
  {
    "id": "tonas-angelo",
    "members": [
      {
        "firstName": "Angelo",
        "lastName": "Tonas"
      },
      {
        "firstName": "Paige",
        "lastName": "Tonas"
      }
    ],
    "events": [
      "welcome"
    ]
  }
];
